# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "37565a4906034ddad95e4bc100bd3751"
name = "shApp1"
handle = "shapp1-1"
application_url = "https://sport-quickly-san-install.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "fffff12345test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://sport-quickly-san-install.trycloudflare.com/auth/callback",
  "https://sport-quickly-san-install.trycloudflare.com/auth/shopify/callback",
  "https://sport-quickly-san-install.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
